### ISSUE TITLE
存储可以支持本地硬盘存储吗

### ISSUE THREAD

**Issue by KangEn1994** [besscroft/PicImpact#102]
因为自己有搞了nas所以就没用其他服务

**Comment by besscroft** [comment]
暂时还不支持，我抽空看看怎么在前端弄，前端框架里面我还没写过这功能。

**Comment by KangEn1994** [comment]
> 暂时还不支持，我抽空看看怎么在前端弄，前端框架里面我还没写过这功能。

我直接部署了一下alist，也比较容易，目前已经可以正常使用了  https://picture.kangen.fun:7894/
