### ISSUE TITLE
后台登陆密码忘记了如何处理？

### ISSUE THREAD

**Issue by yufxxz** [besscroft/PicImpact#106]

**Comment by besscroft** [comment]
将数据库中的 `User`  表的 `password` 字段的【值】【更新】为 `51630b15b0cec2da9926af7015db33b7809f9d24959a0d48665b83e9d19216cd5601d08a622a8b2c48709d5bbb62eef6ae76addce5d18703b28965eef62d491b`，然后重启服务即可。

**Comment by yufxxz** [comment]
已经处理好了。

**Comment by yufxxz** [comment]
已经处理好了
请问后续会完善登陆功能吗？
- 忘记密码
- 自定义邮箱账户

**Comment by besscroft** [comment]
不会，因为除了 self-hosted 用户之外，也有很多用户部署在 vercel 之类的平台。在无法确认用户身份的情况下，用户自行更新数据库是最稳妥的方案。
