### ISSUE TITLE
【功能建议】后台批量操作

### ISSUE THREAD

**Issue by ssln5014** [besscroft/PicImpact#113]
- 有的图片失效了，一个一个删的心累，能够增加一个批量操作就好了
- 每次上传都要选择存储策略和相册，如果能够定义一个默认值会不会更好

**Comment by besscroft** [comment]
感谢您的建议~
1、批量删除我会考虑，我需要同时设计移动端的操作，如果移动端交互体验不太方便，可能只会保留PC端的。
2、默认值是个很好的功能，我会抽空加上。

**Comment by ssln5014** [comment]
好的，只有pc端的也很好了



                       
原始邮件
                       
                     

发件人："云心鹤鸣"< ***@***.*** &gt;;

发件时间：2024/9/11 20:28

收件人："besscroft/PicImpact"< ***@***.*** &gt;;

抄送人："ssln5014"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [besscroft/PicImpact] 【功能建议】后台批量操作 (Issue #113)




 
感谢您的建议~
 1、批量删除我会考虑，我需要同时设计移动端的操作，如果移动端交互体验不太方便，可能只会保留PC端的。
 2、默认值是个很好的功能，我会抽空加上。

**Comment by ssln5014** [comment]
> 感谢您的建议~ 1、批量删除我会考虑，我需要同时设计移动端的操作，如果移动端交互体验不太方便，可能只会保留PC端的。 2、默认值是个很好的功能，我会抽空加上。
![Screenshot_20240911_235735](https://github.com/user-attachments/assets/f6482643-3fae-447f-bf1f-582c2990201e)

手机界面十分不错，布局合理美观，有没有计划支持PWA呢？那样的话启动速度和流畅度都会更好点。
