### ISSUE TITLE
感觉需要一个设置，可以把复制原图链接和下载原图关了

### ISSUE THREAD

**Issue by yangge2333** [besscroft/PicImpact#131]

**Comment by besscroft** [comment]
不是很能理解，这样有啥意义......

**Comment by hexgu** [comment]
其实我也是这么想的，我其实是不太乐意将原图进行分享，或者说大部分摄影师为了防盗图的都应该会减少原图在互联网中传播吧

从其他的角度来讲，有一个下载按钮，会给授权下载人该图片的使用权的感觉

所以我**支持该提案**，因为有些用户可能只是单纯的想展示图片

我建议增加让用户选择是否允许二次转载、下载、使用，用户不允许的话在信息栏中显示禁止转载声明，如果用户允许的话再显示原图下载链接。这种选择建议是全局、或者图库层级的。下载时提供声明协议告知（比如CC BY-NC-SA 4.0啥的）

**Comment by besscroft** [comment]
@hexgu 这么说的话，那确实说的通了，这个需求可以加上，但是需要稍微调整下。

**Comment by soxft** [comment]
https://github.com/soxft/PicImpact/tree/feature/allow_share 在该分支完成了此功能，但由于对 Prisma 的不熟悉，还需待我测试一下
