### ISSUE TITLE
自建仓库默认走https协议

### ISSUE THREAD

**Issue by zimBlue** [besscroft/PicImpact#135]
你好
我这里是自建了一个minio仓库 接口使用的时候是 192.168.X.X:9000 但是代码中大部分获取client的地方都是写死了https开头的
例如  
endpoint: endpoint.includes('https://') ? endpoint : `https://${endpoint}`,
也许可以改成 
endpoint: /^https?:\/\//.test(endpoint) ? endpoint : `https://${endpoint}`

**Comment by besscroft** [comment]
您自建的不套一个 https 的嘛......

**Comment by zimBlue** [comment]
您说的也是个办法 我现在用nginx加了个https 也可以使用了 但一开始的时候也只打算让仓库内网访问 现在开放到公网有点隐隐不安 不过也可以看看minio加密部分来加强下
