### ISSUE TITLE
Vercel部署连接PgSQL相关问题(部署成功分享，非bug)

### ISSUE THREAD

**Issue by ShellMonster** [besscroft/PicImpact#136]
**简述**：本内容非bug反馈，旨在分享部署成功的情况！

**部署失败流程**：本人使用示例给出的`postgres://账号:密码@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres`替换上自己的地址和
账号密码时，部署后一直无法正常打开，试了3次+；

**部署成功流程**：后使用DataGrip测试pgsql数据库的连接正常，对比发现DataGrip使用的是`postgresql:`开头；
重新尝试部署，可以正常登录使用了。

**如有遇到的可以试试看。**

**补充说明**：后续部署中未将 `Build Command 设置为 pnpm run build:vercel` 即正常访问了。

**Comment by besscroft** [comment]
这里需要补充一点：`Build Command 设置为 pnpm run build:vercel` 是因为需要让 prisma 对数据库表结构进行一个初始化操作，以及生成 prisma client 和类型结构文件。只有第一次或涉及到数据库表结构更新时，才需要这个命令。其他时候某些步骤 vercel “似乎”会自动完成。

不过文档里面确实要改了，因为我复制的字符串，还是 supabase 调整 api 之前的了，容易引起用户误解。
