### ISSUE TITLE
[功能建议] 增加 RSS 支持

### ISSUE THREAD

**Issue by hexgu** [besscroft/PicImpact#137]
最近 [RSSNext/Follow](https://github.com/RSSNext/Follow) 这个项目特别火，Follow 有一个图片流的功能特别好 。我觉得和本项目特别契合。

![image](https://github.com/user-attachments/assets/f8f3666c-5878-4eb6-b6d0-1bbaf26c1ffe)

**Comment by besscroft** [comment]
这个提议不错，可以按照现有的提供订阅页面或 tag 的形式来输出内容。我会抽空研究并在 v2 分支加上该内容，就是太忙可能会有点慢。

**Comment by hexgu** [comment]
@besscroft [Follow](https://github.com/RSSNext/Follow) 还支持列表的功能，我们也可以收集大伙的站点，维护出来一个订阅合集

**Comment by hexgu** [comment]
> 这个提议不错，可以按照现有的提供订阅页面或 tag 的形式来输出内容。我会抽空研究并在 v2 分支加上该内容，就是太忙可能会有点慢。

在开发该功能的时候有一点您要留意

Follow 有一个订阅源所有权认证的功能，需要在 RSS 输出中添加类似以下的标签

```
<follow_challenge>
    <feedId>xxx</feedId>
    <userId>xxx</userId>
</follow_challenge>
```

**Comment by besscroft** [comment]
我在开发环境试了一下，是没问题的。但是我不清楚 follow 需要的 xml 格式是咋样的，目前订阅后显示会有点奇怪.......

**Comment by besscroft** [comment]
![image](https://github.com/user-attachments/assets/b4391123-f560-4dea-bc83-f45f553339a2)
我试了几个在线 RSS 阅读器，都能解析出图片，但在 Follow 客户端不显示，怀疑是格式问题？

**Comment by hexgu** [comment]
> follow 需要的 xml 格式是咋样的

这个部分的格式您可以参考 [DIYgod/RSSHub](https://docs.rsshub.app/zh/joinus/advanced/advanced-feed) 的输出格式，但是 RSSHub 的输出标准也是 RSS 2.0 ，我看了一下您的 feature-rss 应该是没问题的。


>我试了几个在线 RSS 阅读器，都能解析出图片，但在 Follow 客户端不显示

在 Follow 客户端能成功订阅但是不显示图片是吗？

**Comment by besscroft** [comment]
![image](https://github.com/user-attachments/assets/f38bca0e-a6f0-4ced-8433-6d47a3ff703c)
是的，不显示，应该还是输出的格式有哪里不对劲。

**Comment by besscroft** [comment]
不确定 follow 的服务端是否有缓存，网站 rss.xml 更新后，follow 这边并没有变化......

**Comment by besscroft** [comment]
![image](https://github.com/user-attachments/assets/524bb663-ca20-4b53-9e9f-596cbf351f9c)
好了，我确定是缓存的问题了，换了个域名，显示一切正常...........

**Comment by besscroft** [comment]
![image](https://github.com/user-attachments/assets/0ba58f5e-362c-4996-af1c-22e5463a5cff)
现在可能需要做的，就是确定格式，什么样的格式好看。以及完善订阅源所有权功能。

**Comment by hexgu** [comment]
> 不确定 follow 的服务端是否有缓存，网站 rss.xml 更新后，follow 这边并没有变化......

follow 服务端有一个小时的缓冲，而目前 rss.xml 更新后 follow 只会用增量更新，老的 rss 暂时不会修改。

**Comment by hexgu** [comment]
>现在可能需要做的，就是确定格式，什么样的格式好看。以及完善订阅源所有权功能。

就是有几点，icon 和 author 是用站点数据还是用户数据，如果是用用户数据的话那用户的界面还得改。

然后我的想法是只输出照片信息和版权，然后 Exif 信息引流到网站去好了

```
{照片描述}

作者：{@xxx}{@xxx}

[查看 Exif 信息](https://xxx.xx/xxxx)
```
