### ISSUE TITLE
从 v1 导入照片

### ISSUE THREAD

**Issue by Zheaoli** [besscroft/PicImpact#143]
有办法从 v1 中导入照片么？

**Comment by Zheaoli** [comment]
阿 sir 不是吧！你这是坑死我了。。。我来写脚本吧， assign 给我吧

**Comment by besscroft** [comment]
真的真的非常抱歉，我的问题，没处理好😭

**Comment by Zheaoli** [comment]
> 真的真的非常抱歉，我的问题，没处理好😭

我要揍你呜呜呜呜。。。。（（（（

**Comment by Zheaoli** [comment]
算了，看你也是粉毛头像的份上不揍了。。

**Comment by besscroft** [comment]
给您磕一个（
![image](https://github.com/user-attachments/assets/d08f5eb0-ad39-48a0-9f85-7f5ee4ffb099)
