### ISSUE TITLE
docker部署问题

### ISSUE THREAD

**Issue by 8824PPZ** [besscroft/PicImpact#156]
docker日志如下：

npm warn exec The following package was not found and will be installed: prisma@5.17.0
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-southeast-1.pooler.supabase.com:6543"
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-southeast-1.pooler.supabase.com:6543"

然后就卡主不动了，大佬求解

**Comment by besscroft** [comment]
感谢您的反馈，我会尝试复现并解决。

**Comment by 8824PPZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/33775809/386460747-7bf2761a-9c0a-4e51-83bf-aa42a10a7b33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTU5MDAsIm5iZiI6MTczMTY1NTYwMCwicGF0aCI6Ii8zMzc3NTgwOS8zODY0NjA3NDctN2JmMjc2MWEtOWMwYS00ZTUxLTgzYmYtYWE0MmExMGE3YjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NjI2NDQ1YjMxMDMwM2Y4OTM2ZmNhNDJkMDA4ZjJiNGRlMzFlZjE1YmU4MGY2OWM4ZGJjM2YzOTk5NjRiOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ryqatvwYES_sZWyUajbDiKN6Yx4TGqywt30HG3KtHcE)
> 
> ![image](https://private-user-images.githubusercontent.com/33775809/386460477-852112d3-5334-4f04-a641-5faa690dda28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTU5MDAsIm5iZiI6MTczMTY1NTYwMCwicGF0aCI6Ii8zMzc3NTgwOS8zODY0NjA0NzctODUyMTEyZDMtNTMzNC00ZjA0LWE2NDEtNWZhYTY5MGRkYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZDk4NDdiZmIyM2ZiYTRiOGNlYTRjZDNlNzc1MDM4MGFmYmRhZjQ1NWMyMTVjNWM3YTU3OTRiNWFlMTRmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.REPAOf3xo2cK58_eVt1Diti1VlDmoAiX4eXkP57-GoU)
> 
> 您可以在 supabase 控制面板选择链接方式为：`Session mode`，我在测试环境的 k8s 测试了一下，容器可以正常运行，您可以重新试试，也可以稍后尝试新版本。

非常感谢，修改成`Session mode` 之后就可以了
