### ISSUE TITLE
多个文件上传后只会显示5张图正在上传中

### ISSUE THREAD

**Issue by 8824PPZ** [besscroft/PicImpact#159]
![image](https://github.com/user-attachments/assets/3bb17654-41be-4640-a998-d97b4f5326a3)

不知道这个是bug还是设计就是这样的。
上传完后也只会显示五张图，但实际上传了大概有10几张图吧。
![image](https://github.com/user-attachments/assets/e549b174-8fd0-42ac-9594-9457f9b2d784)

**Comment by 8824PPZ** [comment]
> 设计如此，您可以点击页面右上角的问号按钮查看解释。

但是上传到那个相册里面，在展示页面不会有显示。然后我又测试了把上传的照片改绑到其他相册才能够显示。这个又是什么问题？

**Comment by besscroft** [comment]
上传完毕的图片，默认不显示的啊，要自己去图片管理点开显示按钮。一上传完就在相册页面展示更奇怪不是嘛......

**Comment by 8824PPZ** [comment]
> 上传完毕的图片，默认不显示的啊，要自己去图片管理点开显示按钮。一上传完就在相册页面展示更奇怪不是嘛......

我是点了显示按钮的，但是在展示页面那里不显示。

**Comment by 8824PPZ** [comment]
我试着重新绑定回上传的那个相册，但是那个相册里面的照片依旧是不显示的。换到其他相册还是可以显示的。不知道你们有遇到这个问题吗

**Comment by besscroft** [comment]
我这边没法复现，能提供更多信息吗？比如相册路由，上传请求参数之类的。

**Comment by 8824PPZ** [comment]
> 我这边没法复现，能提供更多信息吗？比如相册路由，上传请求参数之类的。

相册路由是不支持    `/xxx/xxx` 这样的吗

**Comment by besscroft** [comment]
相册路由不支持 `/xxx/xxx` 格式。

**Comment by 8824PPZ** [comment]
好吧
