### ISSUE TITLE
迁移至v2问题

### ISSUE THREAD

**Issue by minimua** [besscroft/PicImpact#162]
已经执行了迁移，重新启动项目还是会判断数据结构不一致需要reset schema

![image](https://github.com/user-attachments/assets/bc715c4f-c2a1-4727-8ecf-7cc4c0003cdc)

不知道是不是因为，v1几个表用的create_time，v2用的created_at，迁移脚本是直接迁移了，没特殊处理这块 (好吧其实是gpt说的)
![image](https://github.com/user-attachments/assets/f585b0c3-eab1-45d9-8d53-8e3a9fbdbd3a)

**Comment by besscroft** [comment]
你是不是在同一个数据库执行的操作？迁移是需要准备新数据库的，您可以在数据库创建一个新的库。

**Comment by minimua** [comment]
是两个数据库，这个supbase新建一个project应该就是新的数据库吧
![image](https://github.com/user-attachments/assets/a8c1dcdd-2f85-4644-9cbe-702f7ee86b92)

![image](https://github.com/user-attachments/assets/29cc120f-0eba-43fc-81b3-0558c3fc783e)

**Comment by besscroft** [comment]
这个问题就有点奇怪了，迁移脚本只是迁移数据而已，并不影响表结构。

迁移步骤是这样的：
1、准备一个新数据库，然后部署新版本，部署时会自动在新数据库初始化表结构。
2、部署成功后，执行迁移脚把数据从 v1 版本迁移到 v2 版本。

您可以说一下，您的步骤，我看看可能问题出在哪儿。

**Comment by minimua** [comment]
![image](https://github.com/user-attachments/assets/59529e0a-bb71-4fc9-a57a-79f686dd3b76)
我大概知道了，我发现我的v1版本数据库中也有v2版本的表，不确定是不是同步了v2的代码之后，再第一次启动的时候，环境变量的数据库url没改，就把v2的表初始化到了v1中。

然后使用新的数据库部署成功后，执行了迁移脚本，这一步是不是因为有几个表只是大小写不同，迁移时导致了问题？

目前我是先把数据库结构搞一致了，项目启动时不再需要reset schema

**Comment by besscroft** [comment]
![image](https://github.com/user-attachments/assets/e9279e87-58d4-4a02-9fc6-a9525c7e87be)
也许是的？检测 `Database schema` 也是工作流程之一，数据库配置应保持一致。
