### ISSUE TITLE
手机拍照上传exif信息问题

### ISSUE THREAD

**Issue by minimua** [besscroft/PicImpact#174]
为什么我手机（iPhone15Pro）拍的照片，上传后的光圈和焦距都是这两个数 😔

![image](https://github.com/user-attachments/assets/46f33dbd-1b8e-49d2-b6a2-9b6ffc0a2a8a)

是不是需要自己处理下这数字，我看windows展示的f1.8和7mm
![image](https://github.com/user-attachments/assets/97d13220-73aa-4f6a-9aef-397b2facbd8f)
 
试了几个网站解析的也不一样
![image](https://github.com/user-attachments/assets/e7f9b6cf-2e04-4f1e-a97b-e19fac40ba36)
![image](https://github.com/user-attachments/assets/0f54f819-0dbb-4f9f-bac2-690bf2ac6fbf)

**Comment by besscroft** [comment]
这个需要找库作者提 issue。

**Comment by minimua** [comment]
抱歉，确实库这边就是精度丢失了。
![image](https://github.com/user-attachments/assets/b814ab08-a4b7-4755-b172-91746d32f1f8)

我自己处理了下
https://github.com/besscroft/PicImpact/commit/8c1fcfaf47982769f84fc4e4a9f246993191b3c9

https://github.com/besscroft/PicImpact/commit/8ee26bffa2ce7d0d9c1e5646b30c644c2e927872
