### ISSUE TITLE
[疑似bug?]使用AList API上传的图片URL有问题

### ISSUE THREAD

**Issue by Chun-QiuCC** [besscroft/PicImpact#182]
使用AlistAPI上传的图片URL都会变成 http://localhost/xxxxx ，需要后期自己手动改成正确的Alist URL，上传没有任何问题，如图所示：
![image](https://github.com/user-attachments/assets/ddd157f3-72d4-4c28-86ae-2c60275e5d92)

**Comment by Chun-QiuCC** [comment]
CF R2和 S3 API没有做过测试，并且我在issues里没有找到和我类似的问题，可能是未使用容器或者 Vercel，自行编译部署带来的bug

**Comment by besscroft** [comment]
这里的地址是 alist 接口回传的，您可以尝试直接通过 API 请求来查看返回的数据看看，因为我这边也不清楚你那边是如何部署的 alist。
alist 文档：
[表单上传文件](https://alist.nn.ci/zh/guide/api/fs.html#put-%E8%A1%A8%E5%8D%95%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6)
[获取某个文件/目录信息](https://alist.nn.ci/zh/guide/api/fs.html#post-%E8%8E%B7%E5%8F%96%E6%9F%90%E4%B8%AA%E6%96%87%E4%BB%B6-%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF)

**Comment by Chun-QiuCC** [comment]
> 这里的地址是 alist 接口回传的，您可以尝试直接通过 API 请求来查看返回的数据看看，因为我这边也不清楚你那边是如何部署的 alist。 alist 文档： [表单上传文件](https://alist.nn.ci/zh/guide/api/fs.html#put-%E8%A1%A8%E5%8D%95%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6) [获取某个文件/目录信息](https://alist.nn.ci/zh/guide/api/fs.html#post-%E8%8E%B7%E5%8F%96%E6%9F%90%E4%B8%AA%E6%96%87%E4%BB%B6-%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF)

抱歉，这个问题的确是由于我 alist 配置不当造成的，需要在 alist 配置文件中的 site_url 字段填写站点URL，这样API才能正确返回URL
