### ISSUE TITLE
默认用户名不能修改吗

### ISSUE THREAD

**Issue by zzkuner** [besscroft/PicImpact#188]
默认用户名不能修改吗

**Comment by besscroft** [comment]
`username` 字段因为涉及到初始化，是不能更改的。如果您是指登录时用的邮箱的话，是可以的。没做这个功能，您可以直接去数据库改，做这个功能感觉没啥必要。

**Comment by zzkuner** [comment]
嗯嗯嗯，就是那个默认邮箱，我可以在启动的时候加一些环境变换替换一下吗，还是怎么改

**Comment by besscroft** [comment]
修改 `users` 表的 `email` 的值即可。

**Comment by zzkuner** [comment]
好的
