### ISSUE TITLE
[功能建议]分类标签

### ISSUE THREAD

**Issue by hietsusama** [besscroft/PicImpact#24]
谢谢大佬，
有个小建议，能否添加一个#标签功能。
#2024萤火虫 #手机摄影 etc.
然后可以根据标签展示照片，方便查阅。

**Comment by besscroft** [comment]
@hietsusama 您好！目前后台的“标签”，我是当作路由的形式在用，每个标签对应前端页面的每一个子页面相册。您说的这个 `#标签` 形式的标签，需要和“路由”页面联动吗？

**Comment by hietsusama** [comment]
@besscroft 感谢回复！
目前我在前台顶部看到了首页和时光相册这两个标签。
我的想法是是否可以再增加一个汉堡菜单，作为照片的“标签”来使用。
像我之前所讲，在照片详情的下面加一个标签功能，作为超链接，点击之后可以查看同一个标签的照片。
一个照片也可以同时拥有多个标签。
您的路由和标签应该是指相册级的分类，我的想法是照片级别的分类。

**Comment by besscroft** [comment]
@hietsusama 我得考虑下，是和现有的“标签”联动起来，动态绑定和动态跳转；或者是重新一套独立的逻辑，通过 params 的形式来进行，也就是您指的“汉堡菜单”。点击图片的标签后，跳转到“汉堡菜单”页面，然后携带标签信息（params）过去，再拿到所有拥有这个标签的图片。就我个人而言的话，我更倾向于前者，在我一开始设计时就有考虑过这个问题，所以表结构已经进行了兼容性设计，适配起来也方便不少。

**Comment by hietsusama** [comment]
@besscroft 感谢回复！
另外如果可以兼容国内的对象存储那就再好不过了，比如七牛，又拍之类。
我记得又拍是有免费额度的，对于备案过的朋友应该比较友好。

**Comment by besscroft** [comment]
@hietsusama 国内对象存储可以直接试试 S3 API 的方式，AWS S3 和阿里云 OSS 是可以用的，其它的没试过，理论上只要存储兼容 S3 API，都是能用的。

**Comment by besscroft** [comment]
分类标签功能已实现。

**Comment by hexgu** [comment]
@besscroft 

关于分类标签我有一个想法，我觉得可以加一点预设分类，降低用户的上手难度。很多用户可能没有自己的分类体系，但又想规范分类，这个方案可以弥补。

我目前使用的分类 **动物、黑白、城市风光、时尚、极简抽象、植物、微距、肖像、舞台演出、静物（美食）、水下、建筑、自然风光、人文纪实、航拍、夜景** 。

因为是一个可有可无的功能优化建议，不太确定您对 PicImpact 设计方向，我就在原来的 Issue 讨论，不另起 Issue 了。

**Comment by besscroft** [comment]
我需要考虑预置数据对业务数据的污染影响，业务数据表原则上来说是能不动就不动的。
