### ISSUE TITLE
自建minio作为s3 存储的问题

### ISSUE THREAD

**Issue by super5xy** [besscroft/PicImpact#29]
问题1
自建minio的URL是{域名}/{桶名字}而不是{桶名字}.{域名}的格式,需要把S3Client把forcePathStyle设置为true,能否加一个配置项控制这个属性,同时返回的图片全路径也变成{域名}/{桶名字}

s3Client = new S3Client({
    region: region,
    endpoint: endpoint.includes('https://') ? endpoint : `https://${endpoint}`,
    credentials: {
      accessKeyId: accesskeyId,
      secretAccessKey: accesskeySecret,
    },
    forcePathStyle: true,
  });

问题2 存储路径多了个"/"
![image](https://github.com/besscroft/PicImpact/assets/47842371/cd69b7fd-8428-4167-a65c-650fe7724fda)
![image](https://github.com/besscroft/PicImpact/assets/47842371/c9fd7c03-a581-450d-8e98-b5b8b2db361c)

**Comment by besscroft** [comment]
@super5xy 感谢您的反馈，我会抽空调试解决。

**Comment by super5xy** [comment]
第一个问题已解决,第二个问题还存在,选择首页的时候还是多了一个/,没有走新加的判断 ![image](https://github.com/besscroft/PicImpact/assets/47842371/408cb47f-799a-4585-b7fb-dbd61115ca56)
