### ISSUE TITLE
图片的参数和拍摄时间在哪里设置

### ISSUE THREAD

**Issue by zhilong-12138** [besscroft/PicImpact#35]
<img width="182" alt="image" src="https://github.com/besscroft/PicImpact/assets/46955133/1a05f7db-ab86-409f-be35-7a07f8983fd7">

**Comment by besscroft** [comment]
您好，在上传图片时，会读取图片的 EXIF 信息，如您的图片未携带相关信息，是无法正确获取到的。

**Comment by zhilong-12138** [comment]
> 您好，在上传图片时，会读取图片的 EXIF 信息，如您的图片未携带相关信息，是无法正确获取到的。

好的，感谢
