### ISSUE TITLE
建议搞一个example站点

### ISSUE THREAD

**Issue by yray680** [besscroft/PicImpact#37]
摄影爱好者太需要这样的了。

**Comment by besscroft** [comment]
不是俺没资源搭建，而是公开一个能登录的 example 站点，大概率会被玩坏。会有人上传不合适的照片，也会有人来打广告。我的博客取消评论就是因为一天到晚被程序刷广告评论，我想这个也是同理。
这里有个基于 v0.7.1 版本的演示视频：https://www.bilibili.com/video/BV1xJ4m1P7Rj/
当然，也欢迎您亲自部署尝试！
