### ISSUE TITLE
数据库能不能支持其他比如mysql或者SQlite？

### ISSUE THREAD

**Issue by funet8** [besscroft/PicImpact#38]

**Comment by besscroft** [comment]
兼容起来有点复杂，如果后端是用 Java 写的，我就能很轻松实现。我在 prisma 文档并没有找到合适的，能同时处理 schema、provider 和 migrate 的方案，如果处理不好，可能会对现有用户造成破坏性影响。毕竟还要考虑到不同数据库之间的方言，以及表结构问题。
