### ISSUE TITLE
[功能请求] 支持 Markdown

### ISSUE THREAD

**Issue by hexgu** [besscroft/PicImpact#40]
非常感谢您做的相片集项目，它非常的好用

## 功能说明
在照片描述栏中加入 Markdown 的支持

## 适用场景

1. 我有大量的人像照片，一般情况下我会标明模特的姓名，以超链接的方式指向模特的微博等社交平台（其实就是漫展返图）
2. 我的图片也会在视觉中国、500px、8kraw中同步展出，这样我可以指向这些平台。（但是这个需求并不是照片描述范围里面的，我觉得可能需要再而外再加一个栏目）

## 其他
我在测试的时候注意到照片描述同时会影响左上角的标题，您可能需要权衡这个功能以及实现方式

**Comment by besscroft** [comment]
感谢您的建议。
1、图片指向社交和版权平台，确实是一个不错的提案，我会抽空添加进来。只不过不一定要用 markdown 的形式，这个您有好的 idea 也可以提供。
2、标题和照片描述确实应该拆开，我会进行调整。

**Comment by hexgu** [comment]
> 感谢您的建议。 1、图片指向社交和版权平台，确实是一个不错的提案，我会抽空添加进来。只不过不一定要用 markdown 的形式，这个您有好的 idea 也可以提供。 2、标题和照片描述确实应该拆开，我会进行调整。


那我觉得加两个按钮进来会是不错的选择，但是样式和摆放位置的话可能您得想想，因为您左侧是长条设计，我试了几种排布方式都不是很满意。我的觉得把版权平台置于左侧底部会观感好一点，但是社交平台的摆放位置似乎不是很好挑

不过我有一个挺有意思的想法，您可以直接在右上角在相机信息之上设计一个信息框，类似于下图所示，这样的大小和排布都符合您原先设计，还能解决一下左侧信息栏底部空旷问题。

但是我的这个方案存在一个问题，我个人认为不应该头像放头像，但是不放左边加点东西很难平衡这个设计比例问题
![image](https://github.com/besscroft/PicImpact/assets/85490069/105eb8a6-a446-440e-a840-3a961d8b040a)

**Comment by besscroft** [comment]
Tabs 栏多一个，叫 `版权` 也行，跟 `详情` 和 `Exif` 在一起，这也是一个方案。设计方面要同时考虑 PC 和移动端，确实要想一想。

**Comment by hexgu** [comment]
> Tabs 栏多一个，叫 `版权` 也行，跟 `详情` 和 `Exif` 在一起，这也是一个方案。设计方面要同时考虑 PC 和移动端，确实要想一想。

确实，感觉您这个方案似乎更好
