### ISSUE TITLE
Proposal：支持批量上传、编辑照片

### ISSUE THREAD

**Issue by cospotato** [besscroft/PicImpact#46]
## 背景描述

目前上传页面仅支持一张照片上传（也可能是我的操作不对？），并且每上传完一张照片（指点击“保存”）之后，存储库和相册的选择会被清空，这样导致在不需要编辑任何信息的情况下，上传一张照片至少需要点击 6 次：
- 点击存储库 drop down
- 选择存储库
- 点击相册 drop down
- 选择相册（如果相册多还需要 scroll 若干行）
- 点击拖拽照片
- 点击保存

## 功能描述

1. 上传照片页面支持一次选择多张照片
2. 并行上传照片（*可选）
3. 以列表方式展示上传的照片
4. 使用 drop down 展示原先用于编辑照片信息的部分
5. 支持一些批量设置的参数比方说：Tag

**Comment by besscroft** [comment]
@cospotato Hi!，您可以尝试上传完一张之后，直接上传下一张，无须点击删除按钮。批量上传将会难以设计批量编辑图片信息的部分。

**Comment by cospotato** [comment]
> @cospotato Hi!，您可以尝试上传完一张之后，直接上传下一张，无须点击删除按钮。批量上传将会难以设计批量编辑图片信息的部分。

好的，我尝试一下

**Comment by Zheaoli** [comment]
> 批量上传将会难以设计批量编辑图片信息的部分。

说起来批量上传蛮刚需的，我很多照片不需要标题，只想迁移过来。。现在一张张传还是有点麻了

**Comment by besscroft** [comment]
我看看能不能想办法重新设计一下，图片的自定义编辑信息可以在上传后去编辑，不在上传时做强制性要求。批量上传我还没做过，我下周会抽空研究一下妥善点的方案。
