### ISSUE TITLE
关于vercel部署的一些问题

### ISSUE THREAD

**Issue by Rainmeter1222** [besscroft/PicImpact#52]
前情提要
1、首次接触Vercel这个平台。
2、没有接触过Postgre数据库。

目前遇到的情况
1、点击一件部署后，成功连到github了。
2、在下面的Configure Project中不确定应该填什么值（看到是要填数据库url，但是我怎么去获取这个url呢，这个数据库是在我本地部署呢？还是在哪里部署）。
![image](https://github.com/besscroft/PicImpact/assets/104894251/6f631f2a-619d-4649-b22b-9ae342961c46)
谢谢！

**Comment by Rainmeter1222** [comment]
也是第一次提issue，格式如果有什么不对请见谅

**Comment by besscroft** [comment]
@Rainmeter1222 您好，数据库您可以自行部署，也可以使用云服务商提供的数据库（如 supabase 的数据库，我就用的这个，免费额度够用了），任何方式都可以，只需要保证程序能连接上数据库就行。

环境变量的值可以参考 README 文档中的：https://github.com/besscroft/PicImpact?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2

> 格式不打紧，能描述清楚问题就行。

**Comment by besscroft** [comment]
已更新 Vercel 部署视频，您可参考：https://github.com/besscroft/PicImpact/issues/50

**Comment by Rainmeter1222** [comment]
好的，十分感谢！

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
