### ISSUE TITLE
管理后台删除照片后，后端存储中的对应的照片文件并没有删除，这是 bug 吗？

### ISSUE THREAD

**Issue by 80imike** [besscroft/PicImpact#55]
管理后台删除照片后，后端存储中的对应的照片文件并没有删除

我用的是 alist 做后端存储

这个是这样设计的，还是 bug ？

**Comment by besscroft** [comment]
@80imike 您好，就是这么设计的。删除是逻辑删除，并不会删除真正的数据，不管是存储的图片，还是数据库中的数据都是保留的。数据库中部分业务数据的逻辑删除，只是标记了删除状态而已。
