### ISSUE TITLE
我按照步骤来最后打不开哎

### ISSUE THREAD

**Issue by kjhchouch** [besscroft/PicImpact#62]
我的数据库也连接上了，也有表存在，但是打不开页面

**Comment by kjhchouch** [comment]
![image](https://github.com/besscroft/PicImpact/assets/128597783/9c80adf5-95bc-4d45-bf02-36d207ea0d3e)

**Comment by kjhchouch** [comment]
大佬，救一下

**Comment by besscroft** [comment]
![image](https://github.com/besscroft/PicImpact/assets/33775809/5cdd97f2-add5-4b3b-950b-797124a3ecc1)

请确保您的网络能正常访问 vercel 提供的地址，我这边是可以访问到的。

> 部分地区/运营商，对 vercel 采取了封锁措施（被墙了

**Comment by kjhchouch** [comment]
![image](https://github.com/besscroft/PicImpact/assets/128597783/48a11358-4c7f-4c97-a477-e51ccbb955cf)
我的是这样

**Comment by kjhchouch** [comment]
我知道了，要翻墙才能进啊，有什么办法能不翻墙吗

**Comment by kjhchouch** [comment]
还有一个问题，大佬，我登录之后他不跳转，一直在登录页面

**Comment by besscroft** [comment]
你给项目绑定一个域名呀，没有人用 vercel.app 的子域名的，被墙了还用它干啥。

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
