### ISSUE TITLE
我一直卡在login页面

### ISSUE THREAD

**Issue by kjhchouch** [besscroft/PicImpact#63]
输入账号密码，连接也通了，也有提示登录成功，最后还是重定向到login页面了

**Comment by besscroft** [comment]
你的页面除了你之外没人能进得去，因为需要访问凭证的。不过你这个问题倒是第一次收到反馈，麻烦提供下有用的信息。

**Comment by kjhchouch** [comment]
那我怎么暴漏给别人用呐，佬。
我点登录，然后输入密码，我看网络什么的都是通的，也报了登录成功，最后还是在login页面

**Comment by besscroft** [comment]
我也不明白为什么你部署之后需要 vercel 授权才能访问，要别人访问你得公开才行，或者绑定域名。

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
