### ISSUE TITLE
vercel部署问题

### ISSUE THREAD

**Issue by Rancho-7** [besscroft/PicImpact#69]
根据视频进行了操作：
https://www.bilibili.com/video/BV1Yn4y1d78v/?spm_id_from=333.999.0.0&vd_source=dbfa27b1e750dea2ab905150b6ec78ad
但是部署时报错：
<img width="1025" alt="image" src="https://github.com/besscroft/PicImpact/assets/59016860/4ff48c9c-c2be-40e4-a184-303ce94086fd">
请问这是什么原因？

**Comment by besscroft** [comment]
连接数据库失败，有时候网络抽风是这样的（不确定是 vercel 还是 supabase 的原因），只能重试。

**Comment by Rancho-7** [comment]
> 连接数据库失败，有时候网络抽风是这样的（不确定是 vercel 还是 supabase 的原因），只能重试。

尝试了好几次一直这个问题😭

**Comment by besscroft** [comment]
这个你找我没用，假设环境变量配置正确的情况下，那么极大概率是 supabase 的问题，极小概率是 vercel 的问题，我自己的 vercel dev 环境有时候也这样，您要是压根用不了，建议跟 supabase 提工单。

> 日志信息已经告诉您原因了，您不愿意看我也没办法。

**Comment by Rancho-7** [comment]
> 这个你找我没用，假设环境变量配置正确的情况下，那么极大概率是 supabase 的问题，极小概率是 vercel 的问题，我自己的 vercel dev 环境有时候也这样，您要是压根用不了，建议跟 supabase 提工单。
> 
> > 日志信息已经告诉您原因了，您不愿意看我也没办法。

好的，感谢感谢！

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
