### ISSUE TITLE
照片详情页增加一个 unique 的 permanent link

### ISSUE THREAD

**Issue by Zheaoli** [besscroft/PicImpact#71]
具体的场景如下

比如我这样的站点 https://photos.manjusaka.me/ 有很多我的照片

我想将某张照片分享给朋友，预期的行为是打开这个 link 就能进入照片的详情页

目前还是直接 SSR 的 page component，不太支持分享照片给朋友

**Comment by besscroft** [comment]
这个功能确实，我觉得可以有。单纯的根据链接，比如通过 `https://pic.example.com/preview/example.jpg` 或 `https://pic.example.com/?id=1` 访问网站并弹开详情页，并不算太难。

我设想的流程是这样：点击图片，弹出详情 Dialog，然后点击复制/分享。朋友拿到分享的链接后，直接访问，服务端会重定向至首页，然后客户端弹出详情 Dialog（具体实现细节以及能否实现我还需要评估一下）。关闭详情后，就是正常访问网站的使用流程了。

如果采用链接的形式，可能需要在数据库维护映射；如果是路由参数形式（id），是不需要数据库来维护的，算是各有利弊。

我会抽空弄一下，如果您有好的 idea 也欢迎提供！
