### ISSUE TITLE
Alist api优化

### ISSUE THREAD

**Issue by bestruirui** [besscroft/PicImpact#73]
使用alist作为储存时，上传文件返回的是解析后的直链，这个直链有效期不长，希望可以优化为alist的链接，而不是alist解析后的直链

**Comment by besscroft** [comment]
不太明白您的意思，我目前是通过 [POST 获取某个文件/目录信息](https://alist.nn.ci/zh/guide/api/fs.html#post-%E8%8E%B7%E5%8F%96%E6%9F%90%E4%B8%AA%E6%96%87%E4%BB%B6-%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF) 接口来获取的。
