### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by kjhchouch** [besscroft/PicImpact#74]
![image](https://github.com/besscroft/PicImpact/assets/128597783/bfe5e449-653b-4410-9f5a-091584fc068b)
![image](https://github.com/besscroft/PicImpact/assets/128597783/df063a46-d41c-45db-8637-bbe8c7aa5dc1)
大佬，可以帮忙看一下吗

**Comment by besscroft** [comment]
您能尝试获取后端日志看看吗？看看是否图片太大而超过了 vercel 的请求限制。

**Comment by kjhchouch** [comment]
图片就几十kb，后端日志需要再哪里看呀

**Comment by besscroft** [comment]
Vercel 可以查看项目的 Logs。

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
