### ISSUE TITLE
使用docker部署的如何更新版本？

### ISSUE THREAD

**Issue by zhilong-12138** [besscroft/PicImpact#75]
重新拉取部署latest，还是旧版本

**Comment by besscroft** [comment]
![image](https://github.com/besscroft/PicImpact/assets/33775809/5f620909-0c2b-4964-8dc7-9c60375b77f7)
我刚试了下，latest 是最新版本。如您使用 Docker，您可以尝试删除旧的 Images 后，再重新 pull。如果您使用 k8s，可以尝试设置[镜像拉取策略](https://kubernetes.io/zh-cn/docs/concepts/containers/images/)。

> 您也可以直接指定镜像的 tag，如：`besscroft/picimpact:v0.8.4`。

**Comment by zhilong-12138** [comment]
删完旧镜像才想起来，docker仓库被禁用了，老爷们真可恶啊
