### ISSUE TITLE
新增的分享按钮功能，在移动端和电脑端点击后无响应

### ISSUE THREAD

**Issue by 80imike** [besscroft/PicImpact#81]
新增分享按钮功能，在移动端点击后无任何反应

![IMG_20240629_205339](https://github.com/besscroft/PicImpact/assets/1665201/754af19a-64bb-4700-baeb-2ecca87c48c5)

**Comment by besscroft** [comment]
![image](https://github.com/besscroft/PicImpact/assets/33775809/03606f93-280d-480e-8ae7-f0daac399b17)
有些浏览器/设备是不支持该 API 的，我需要您提供更详细的信息，如：设备、系统版本、浏览器以及内核版本。

**Comment by besscroft** [comment]
刚才重新测试过了，基本符合兼容性测试表。PC 端使用 chrome 系正常，iPhone 上使用 safari 测试正常，小米手机自带浏览器无反应，估计是 WebView 的。

**Comment by 80imike** [comment]
> 刚才重新测试过了，基本符合兼容性测试表。PC 端使用 chrome 系正常，iPhone 上使用 safari 测试正常，小米手机自带浏览器无反应，估计是 WebView 的。

的确是小米手机测试的

**Comment by 80imike** [comment]
@besscroft  大佬，我在 pc 端也测试了下分享按钮，也是无反应的，具体报错如下

<img width="1512" alt="image" src="https://github.com/besscroft/PicImpact/assets/1665201/642787c4-6cf7-4902-ad29-4e5920cbb9d8">

**Comment by besscroft** [comment]
![image](https://github.com/besscroft/PicImpact/assets/33775809/b063f864-e12e-4d0e-a149-2ad458a0c8cc)
我艹我服了，都怪厨子（

**Comment by 80imike** [comment]
> ![image](https://private-user-images.githubusercontent.com/33775809/344538281-b063f864-e12e-4d0e-a149-2ad458a0c8cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjE5ODgsIm5iZiI6MTcxOTgyMTY4OCwicGF0aCI6Ii8zMzc3NTgwOS8zNDQ1MzgyODEtYjA2M2Y4NjQtZTEyZS00ZDBlLWExNDktMmFkNDU4YTBjOGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmUwOTU5MjA2NmJjYmM1N2ZiMmYwNjIwM2JjMjM0YjUxNGM0MmVhOTkxNTY4NThkNjA4MTM0YTM0ZjlmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEp3XYWrb5xh6zY2_64nSPKKvMKxzTOG7AOljEEryn0) 我艹我服了，都怪厨子（

@besscroft  破案了，要是能支持 mac 就好了
