### ISSUE TITLE
相册绑定功能存在 bug

### ISSUE THREAD

**Issue by 80imike** [besscroft/PicImpact#82]
相册绑定功能存在 bug，当相片上传到非首页这个分类时，通过绑定相册功能无法选首页这个分类

![Screenshot_2024-06-29-20-47-46-132_mark via-edit](https://github.com/besscroft/PicImpact/assets/1665201/a74924b2-a70a-4529-9b60-e27ca7d91e56)

**Comment by besscroft** [comment]
感谢您的反馈，我会抽空复现并解决！
