### ISSUE TITLE
首页预览 URL 优化

### ISSUE THREAD

**Issue by Zheaoli** [besscroft/PicImpact#87]
目前的格式是这样

https://photos.manjusaka.me/_next/image?url=https%3A%2F%2Fimage.r2.manjusaka.me%2Fpicimpact%2Fimages%2Fpreview%2FDSC_4981.jpg&w=3840&q=25

本质上是用 Next 的 Backend Server 代理了一层，有这样一些问题

1. CDN cache 不亲和
2. 容易使防盗链设置失效，（比如我的规则是这样 `(not http.referer contains "manjusaka.me" and http.host contains "image.r2.manjusaka.me" and not http.referer contains "manjusaka.blog" )` ，而 next backend 直接请求的话，就会 403 导致首页渲染白屏

**Comment by besscroft** [comment]
感谢您的反馈，我大概明白你的意思了，我去社区找一下解决方案。

**Comment by besscroft** [comment]
测试了一下预览的图片 Cf-Cache-Status 为： `DYNAMIC`，而详情页的是：`HIT`，根据[Cloudflare缓存文档](https://developers.cloudflare.com/cache/concepts/cache-responses/#dynamic)来看确实是没有命中。不知道是不是我测试不够严谨，但测下来发现[缓存行为](https://nextjs.org/docs/app/api-reference/components/image#caching-behavior)确实没生效。似乎已经是社区争论了很久的问题，`next/image`挺好用，性能也尚佳，但是配置不够灵活，解决不了的话我会尝试采用其它方案。

**Comment by besscroft** [comment]
关于CORS 策略，拿我自己的站点测试来说，根据[配置跨域资源共享 (CORS)](https://developers.cloudflare.com/r2/buckets/cors/)配置后是正常的：
![image](https://github.com/besscroft/PicImpact/assets/33775809/6e11aa4c-b543-4e7f-919d-f5dd06a3d78a)
这个我没有复现出来，我猜测是否配置了规则里面的[Origin Rules](https://developers.cloudflare.com/rules/origin-rules/)，有的话可以提供一下详细信息，最好是截图。

**Comment by Zheaoli** [comment]
> 关于CORS 策略，拿我自己的站点测试来说，根据[配置跨域资源共享 (CORS)](https://developers.cloudflare.com/r2/buckets/cors/)配置后是正常的： ![image](https://private-user-images.githubusercontent.com/33775809/344480439-6e11aa4c-b543-4e7f-919d-f5dd06a3d78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjY3OTcsIm5iZiI6MTcxOTc2NjQ5NywicGF0aCI6Ii8zMzc3NTgwOS8zNDQ0ODA0MzktNmUxMWFhNGMtYjU0My00ZTdmLTkxOWQtZjVkZDA2YTNkNzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE2NTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzdhMTdhNTNhNjMxNWQ2ZTFkMjNiZWI4YTBkMGMzZWY4ZTM3MjdmOGIyY2M4OTFkYzQ1Mzc5NTFiMDc0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bywr-6Cxn2Oy7U13SfW6jW15Qb4mM0b8_U-IRFcqiOk) 这个我没有复现出来，我猜测是否配置了规则里面的[Origin Rules](https://developers.cloudflare.com/rules/origin-rules/)，有的话可以提供一下详细信息，最好是截图。

这个其实不是 CORS 的问题

是 CF WAF 策略的问题，这里利用 WAF 能够更好的减少流量的费用
