### ISSUE TITLE
照片详情页新增方向键快捷键

### ISSUE THREAD

**Issue by Zheaoli** [besscroft/PicImpact#92]
目前照片浏览过程是这样

1. 进入相册
2. 点开一张照片
3. 点击关闭
4. 点开下一张照片

如果这里能支持快捷键，方向键切换照片的话，那么能省去3/4 的步骤，方便很多

**Comment by besscroft** [comment]
引入灯箱组件估计是不好做了，不然现有的功能没啥意义。我觉得可以增加切换按钮，根据当前图片在 array 内的索引进行定位，然后增减索引取出对应的值来达到切换图片数据的目的。我有空会加上。
相关 issues：https://github.com/besscroft/PicImpact/issues/64
