### ISSUE TITLE
访问首页存在 500 错误

### ISSUE THREAD

**Issue by 80imike** [besscroft/PicImpact#94]
虽然页面能打开，但访问首页的请求存在 500 错误。

<img width="1389" alt="image" src="https://github.com/besscroft/PicImpact/assets/1665201/9b3141d8-e520-4ffe-9307-35a81b3918d2">

<img width="1058" alt="image" src="https://github.com/besscroft/PicImpact/assets/1665201/908ce557-8af2-4486-b6ac-d5dccff8829a">

这个错误会导致首页加载时存在一定延时会监控健康检查不通过  

还是需要修复下，大佬 @besscroft

**Comment by besscroft** [comment]
如果是不支持 `Navigator: share() method` API 的浏览器访问的话，会在控制台可后端出现 500 错误的日志，但是不会影响浏览器上的任何访问使用。我暂时没找到方法 catch 掉错误，看您能否将健康检查的请求 UA 改成其它支持的类型？
