### ISSUE TITLE
无法连接supabase的Postgre数据库，国内服务器需要搭梯子吗？

### ISSUE THREAD

**Issue by ww1126811502** [besscroft/PicImpact#95]
目前配置supabase的Postgre数据库后，docker拉起后的log会一直卡在这里：

ubuntu@VM-12-9-ubuntu:~/alist$ docker logs 9fd1a7098c3b
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-northeast-1.pooler.supabase.com:6543"

试着ping了一下发现确实ping不到，我是不是可以考虑使用其他的Postgre链接

**Comment by besscroft** [comment]
你都能访问到这里了，是什么原因我想不必多说。程序本身支持任何兼容 pg 的数据库，用其它的是一样的。

**Comment by ww1126811502** [comment]
done
