### ISSUE TITLE
Cloudflare R2 上传后的图片地址错误

### ISSUE THREAD

**Issue by fzred** [besscroft/PicImpact#99]
这是上传后网站显示的地址

<img width="690" alt="iShot_2024-07-08_01 25 26" src="https://github.com/besscroft/PicImpact/assets/7991717/c8ec689a-71cd-42e4-a04d-a625a3e6e077">

这是R2上显示的访问的地址
<img width="708" alt="iShot_2024-07-08_01 25 12" src="https://github.com/besscroft/PicImpact/assets/7991717/c055cdad-619a-45ed-965a-95bc55f97a72">

配置
<img width="699" alt="iShot_2024-07-08_01 28 12" src="https://github.com/besscroft/PicImpact/assets/7991717/a59ff1c7-8308-4fcc-8038-3e88a5a847cc">

 是我哪里配置错了吗？

**Comment by besscroft** [comment]
没发现哪里有问题。。。

**Comment by fzred** [comment]
实际的访问路径 / 变成了 %2F

**Comment by fzred** [comment]
另外 r2 的访问路径多了 photos ，应该是bucket的名字

**Comment by besscroft** [comment]
> 实际的访问路径 / 变成了 %2F

这里没有任何理由需要编码，而且能够保证可读性，能一眼看出来路径。
![image](https://github.com/besscroft/PicImpact/assets/33775809/d47f16b3-31ed-42bc-8914-02e8a1976780)

**Comment by besscroft** [comment]
> 另外 r2 的访问路径多了 photos ，应该是bucket的名字

遗留习惯，且跟其它存储保持一致。

**Comment by fzred** [comment]
但是 r2 的访问连接把 / 转换成了 %2F  ，如果是 / 不能访问

**Comment by besscroft** [comment]
可以访问呀，目前有不少用户都能正常使用，能麻烦您提供一下复现场景吗？我测试一下。
